### ISSUE TITLE
fix the ordering of charts in the menu

### ISSUE THREAD

**Issue by flodoesstuff** [DPS2004/Beatblock-issues#148]
**Is your suggestion related to a problem? Please describe.**
often when im looking for a chart i think "oh! its alphabetical ill just go to where it is" and then its not there because the displayed name is not the name the game uses to sort the charts, the game uses the *folder* name to sort the charts. this can mess up the ordering if the charter, for whatever reason, named the folder differently to the chart itself. another issue i have is that for some reason the alphabet the game uses sorts all capital letters above all lowercase letters, meaning partway through the list it starts over at the beginning of the alphabet because its gotten to all the folders starting with lowercase instead of upper case

**Describe the solution you'd like**
-make the sorting based on chart name instead of folder name if possible
-make the sorting AaBbCc instead of ABCabc (or make it not case sensitive at all)

**Describe alternatives you've considered**
you could ditch the internal chart name entirely and make all the charts in the menu have the folder name instead, then changing the name in the editor with ctrl+i could change the folder name instead of the internal name. this would obviously break all existing charts so i dont think this is the perfect solution, but it is an alternative

**Additional context**
a specific example is the chart "magic theorem" where for some reason the charter just named the folder "theorem" and its like. why

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
Fixed as of early access

**Comment by flodoesstuff** [comment]
i forgot to reply to this at the time but this is only partially fixed. theres now an option to sort by name but 1) sorting options dont save when you leave and reenter the menu and 2) its buggy and can somehow change the positions of the buttons at the bottom of the menu and 3) the sorting is still A-Z-a-z instead of Aa-Zz

**Comment by flodoesstuff** [comment]
oh correction actually the sorting isnt still A-Z-a-z i was just looking at the folders that were all sorted to the very bottom of the list
