### ISSUE TITLE
the start of a hold is defined at the first frame you hit it which is always a tiny bit after the hold actually starts

### ISSUE THREAD

**Issue by flodoesstuff** [DPS2004/Beatblock-issues#166]
**Describe the bug**
if you have an absurdly fast hold, you may notice that the start of the hold is a little bit ahead of where you actually need to hit it

**To Reproduce**
1. Go to the editor
2. make a hold that does hundreds of rotations in one beat (it can also be less if you're Boring)
3. play chart
4. notice you have to hit a hold in a different place every time because this game isnt that consistent with how frames line up (likely due to load times..? i would say its because i have vsync off so my fps is uncapped but i tried with vsync on and its also random lol)

**Expected behavior**
that the start of a hold is explicitly defined at where it is placed in the editor rather than the first frame after it starts

**Screenshots**
something like this lmao,, you can likely do this with far less if you use a more extreme easing such as outCirc which technically has infinite speed at the start of it
![image](https://github.com/user-attachments/assets/d4608fd0-79c5-4eab-a2b3-8d53ceee0785)

**Additional context**
this does not affect gameplay to a very high degree at all unless you're himych and use circ easings like theres no tomorrow

**By submitting this, I am confirming that I have read the [README](https://github.com/DPS2004/Beatblock-issues/blob/main/README.md) and am using the latest version of Beatblock.**

**Comment by OblivionCreator** [comment]
Fixed for the next release. Thanks for the report!

**Comment by flodoesstuff** [comment]
yay!!! this bug actually still happens in +eraby+e connec+ion but with blocks in the part at beat 270 thanks to how fast the player movements are,, even with vsync off my shitty laptop cant get high enough fps to avoid barelies on the notes that are at the same time as cranky moving lol

well i can avoid the barelies but only by intentionally moving the paddle a bit more in the direction that they're about to move in
